version: '3.7'

services:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
           restart: always
    ports:
      - 8899:80
    
    db:
      image: mysql:5.7
      container_name: mysqlserver
      volumes:
        - data:/var/lib/mysql
      environment:   
        MYSQL_DATABASE: dbsukasuka
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin
        MYSQL_ROOT_PASSWORD: admin
      networks:
        - back
